


        console.log( req.body );
        let x = Math.floor((Math.random() * 900) + 100);
        const product = {
            id: Date.now(),
            ref: `PK-${x}-2023`,
            title: req.body.title,
            cover: req.body.cover,
            image: req.body.image,
            image01: req.body.image01,
            image02: req.body.image02,
            image03: req.body.image03,
            price: req.body.price,
            cents: req.body.cents,
            oldPrice: req.body.oldPrice,
            description: req.body.description,
            group: req.body.group
        };
        const product = {
            id: req.body.productId,
            ref: req.body.ref,
            title: req.body.title,
            cover: req.body.cover,
            image: req.body.image,
            image01: req.body.image01,
            image02: req.body.image02,
            image03: req.body.image03,
            price: req.body.price,
            cents: req.body.cents,
            oldPrice: req.body.oldPrice,
            description: req.body.description,
            group: req.body.group
        };

Conjunto Pikituchos Dinossaur

Pikituchos Dinossaur
https://ik.imagekit.io/noely/dinossaur/0-removebg-preview__2_.png?updatedAt=1679897638456
https://ik.imagekit.io/noely/dinossaur/3.webp?updatedAt=1679897677594
https://ik.imagekit.io/noely/dinossaur/0.webp?updatedAt=1679897666346
https://ik.imagekit.io/noely/dinossaur/1.webp?updatedAt=1679897681770
https://ik.imagekit.io/noely/dinossaur/2.webp?updatedAt=1679897659954
49
90
89,90
Conjunto Meninos
O Conjunto Infantil Pikituchos Dinossaur é composto por Camiseta em Meia Malha e Bermuda em Moletom com modelagem tradicional e estampa em relevo.